"""ratings and reports

Revision ID: 2851ee096757
Revises: f6c0fe9998a5
Create Date: 2026-08-14 19:06:29.098044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2851ee096757'
down_revision = 'f6c0fe9998a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reporter_user_id', sa.BigInteger(), nullable=True),
    sa.Column('target_type', sa.Enum('listing', 'broker', name='report_target_type'), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Enum('fraud', 'spam', 'inappropriate', 'wrong_info', 'other', name='report_reason'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved_action', 'resolved_no_action', 'dismissed', name='report_status'), server_default='open', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_reporter_user_id'), ['reporter_user_id'], unique=False)
        batch_op.create_index('ix_reports_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_reports_target', ['target_type', 'target_id'], unique=False)

    op.create_table('broker_ratings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('rater_user_id', sa.BigInteger(), nullable=False),
    sa.Column('broker_user_id', sa.BigInteger(), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.Column('stars', sa.SmallInteger(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('stars BETWEEN 1 AND 5', name='ck_ratings_stars_range'),
    sa.ForeignKeyConstraint(['broker_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rater_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['message_threads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rater_user_id', 'broker_user_id', name='uq_ratings_rater_broker')
    )
    with op.batch_alter_table('broker_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broker_ratings_broker_user_id'), ['broker_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_broker_ratings_rater_user_id'), ['rater_user_id'], unique=False)
        batch_op.create_index('ix_ratings_broker_recent', ['broker_user_id', 'id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broker_ratings', schema=None) as batch_op:
        batch_op.drop_index('ix_ratings_broker_recent')
        batch_op.drop_index(batch_op.f('ix_broker_ratings_rater_user_id'))
        batch_op.drop_index(batch_op.f('ix_broker_ratings_broker_user_id'))

    op.drop_table('broker_ratings')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_target')
        batch_op.drop_index('ix_reports_status_created')
        batch_op.drop_index(batch_op.f('ix_reports_reporter_user_id'))

    op.drop_table('reports')
    # ### end Alembic commands ###
