"""phase-1-to-6 baseline

Revision ID: 58d9acfeb146
Revises: 
Create Date: 2026-08-12 20:51:02.387045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d9acfeb146'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('buyer', 'broker', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    op.create_table('broker_profiles',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('goeic_registration_number', sa.String(length=64), nullable=True),
    sa.Column('registration_document_path', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', name='verification_status'), server_default='pending', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.BigInteger(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('broker_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broker_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('listings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('broker_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_egp', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('area_m2', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('governorate', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('property_type', sa.Enum('apartment', 'house', 'villa', 'land', 'commercial', name='property_type'), nullable=False),
    sa.Column('status', sa.Enum('active', 'sold', 'expired', 'hidden', name='listing_status'), server_default='active', nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duplicate_suspected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('duplicate_of_listing_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duplicate_of_listing_id'], ['listings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_broker_id'), ['broker_id'], unique=False)
        batch_op.create_index('ix_listings_last_confirmed', ['last_confirmed_at'], unique=False)
        batch_op.create_index('ix_listings_status_location', ['status', 'governorate', 'city'], unique=False)

    op.create_table('listing_documents',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('listing_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('title_deed', 'no_liens', 'tax_clearance', name='document_kind'), nullable=False),
    sa.Column('state', sa.Enum('self_reported', 'pending', 'verified', 'rejected', name='document_state'), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.BigInteger(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'kind', name='uq_listing_docs_listing_kind')
    )
    with op.batch_alter_table('listing_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_documents_listing_id'), ['listing_id'], unique=False)

    op.create_table('listing_photos',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('listing_id', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('phash', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_photos_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index('ix_listing_photos_listing_sort', ['listing_id', 'sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_photos_phash'), ['phash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_photos_phash'))
        batch_op.drop_index('ix_listing_photos_listing_sort')
        batch_op.drop_index(batch_op.f('ix_listing_photos_listing_id'))

    op.drop_table('listing_photos')
    with op.batch_alter_table('listing_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_documents_listing_id'))

    op.drop_table('listing_documents')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index('ix_listings_status_location')
        batch_op.drop_index('ix_listings_last_confirmed')
        batch_op.drop_index(batch_op.f('ix_listings_broker_id'))

    op.drop_table('listings')
    with op.batch_alter_table('broker_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broker_profiles_user_id'))

    op.drop_table('broker_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
